apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbtvuelo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kbtvuelo
  template:
    metadata:
      labels:
        app: kbtvuelo
    spec:
      containers:
        - name: kbtvuelo-app
          image: kbtvuelo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/kbtvuelo"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: kbtvuelo-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: kbtvuelo
  type: LoadBalancer